package main

// This package is a simple gRPC server implementation of the service declared
// in internal/proto/example/example.proto, using stub code generated by the
// proto compiler.

import (
	"context"
	"flag"
	"fmt"
	"log"
	"net"

	pb "github.com/colin-valentini/go/internal/proto/example"
	textpb "github.com/colin-valentini/go/internal/proto/example/textproto"
	"google.golang.org/grpc"
)

// Check that the server implementation actually implements the gRPC interface.
var _ pb.HelloWorldServer = (*helloWorldServerImpl)(nil)

type helloWorldServerImpl struct {
	pb.UnimplementedHelloWorldServer
	cannedResponses map[pb.Language]*pb.GreetingResponse
}

func newServer() *helloWorldServerImpl {
	return &helloWorldServerImpl{cannedResponses: textpb.GetCannedResponses()}
}

func (s *helloWorldServerImpl) GetGreeting(
	ctx context.Context, req *pb.GreetingRequest,
) (*pb.GreetingResponse, error) {
	log.Printf("Handling GetGreeting request with id: %d", req.GetId())
	if req.GetId() == 69420 {
		if res, ok := s.cannedResponses[req.GetLanguage()]; ok {
			return res, nil
		}
		return nil, fmt.Errorf("invalid language: %q", req.GetLanguage().String())
	}
	return &pb.GreetingResponse{Message: "Wassup!"}, nil
}

var port = flag.Int("port", 50051, "The server port")

func main() {
	flag.Parse()
	lis, err := net.Listen("tcp", fmt.Sprintf("localhost:%d", *port))
	if err != nil {
		log.Fatalf("failed to listen: %v", err)
	}
	var opts []grpc.ServerOption
	log.Println("Constructing server instance...")
	grpcServer := grpc.NewServer(opts...)
	log.Println("Registering server instance...")
	pb.RegisterHelloWorldServer(grpcServer, newServer())
	log.Println("Starting server...")
	if err := grpcServer.Serve(lis); err != nil {
		log.Fatalf("failed to serve: %v", err)
	}
}
