on:
  push:
    branches:
      - main
  pull_request:
name: CI
jobs:
  build:
    name: Build, Test, Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.5'
      - name: Install Dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
          go install ./ ...
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build
        run: go build .
      - name: Vet
        run: go vet .
      - name: Lint
        run: golint .
      - name: Format
        run: gofmt .
      - name: Test
        run: go test ./...