on:
  push:
    branches:
      - main
  pull_request:
name: CI
jobs:
  golangci:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Go Version
        run: go version
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: Test
        run: go test -race ./...