on:
  push:
    branches:
      - main
  pull_request:
name: CI
jobs:
  golangci:
    name: Build, Lint, Vet, Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x
      - name: Go Build
        run: go build ./...
      - name: Go Vet
        run: go vet ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: Test
        run: go test -race ./...